# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Uf3bjsIkEs0PYJeE4jEd3uLXq5IFBK1gCDnNykoQ7LShcxvI0VpYPm9Lix2zpPePnpKGZIexMQd7mxbrMZq+6XmqZg5fO9JsmAJJx0Ra6s8TdguJsUDPrS4+7ogngohRtj1DDfE3djjEZcrpEoFYOFLDxsN2DU1mJW/55VMGvGLa2ONDOcNxZbW6Drql4TaOODXffbX3I6l8tkGmLwCQByu0D4uvxUlpqJUz3C1SpEpKymKqp/YBaAfokFbnicV3FUfytImRlWwUws9QtbDg8BUmmw98+SAP8Hgl2CISVpxQycyNgWlipI+PM2YX/C2GKlARwAFnm3/ME2LFWnChEIqJxHx52n9x9LmI8ydE5IJteV46fSHcXfRhQZHzOtTujv9e/5X9gIVHpHTQ8qyeBsulHXIBvS0ErHhJpPGKHn06HhSB863sHQomvg47XcRCP6ThtDvI2KZtvA6/lUoInOrUeSflOlRYVl/4bGkGKYOpOfpUxhnF8QFIAoUNOVbyCuybsYEbARrlt/Nzc1ZRmItdUcCHbmnvswqVTrhYNWrdxXYfjfNlQQd/A6wyNJeoaYUFaUvcHHU9mJeIN2q/hiqu2XqNK2Dv0D3tVsGMfWpKvjd/5tlTBJmd9FPazLA1bNapMNG1sPg/l5/CojdFjwv02hE0A+09pC+82V/McK0="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
