# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Ht/VBKmp/R77UplrhkbU0yoBhvVMTMmBKUbFli4E8B9tXh0ibnM3gd5CBKyUqWmQTW1qRudyR1ILgEhYsufr6OQu/ILlblYmls9hjfnUo0CB9XJb3EmJhlsbzweVO8s2DLZXmNEadOnaVGOvQ96ZPFI4GLxI4kA1mMtCwQvoEdt2W+zEGMYonaTzAsJosVvl3Ung1a9oMZWiro6ygyfBxr1G2GBCGUKiyU3XuB30ZOm6eAITQVApZQpG9LH8Fy+MXXUBGVbj0tkWTnX27aH5FPFngFLYBayS3x8jPLJ9jCsGC4VAPnadCjIKxK7q6r78xg9Y7DKoYgjNKwJBYZldvHT/bRrs9GvF+GkJ5zoFDkbZJJ3icPWyUuodLoLyRQllI2O9bRr1zianPiG+/VYFxita4HDPx4T8QXHTIUY9/uhC33n7ucQIS/qMYPZ59cdg15sJXpWsf1QkiCLA1ns9bq7YWR/EVNjYexuWrPqpdY2g/TMsHj0JLJv22H+IUNQSHlVoUgDEuLgw14rrYtoMOSAdPZ/HxzzaUthN3hnn0d2QSZwy2eP/8IYB8YBch8HyF1bjhC+pgHQZGxf/4mbEOcUZQMswiqzLtnlxidAEh04aEnLrsE37v1l0uGfk69t3lQ9uZkQFsoSYSEOQHggyGCUSwjPICQxCjfWEdAOmH3s="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
