travis:
  secure:
    BINSTAR_TOKEN: Uf3bjsIkEs0PYJeE4jEd3uLXq5IFBK1gCDnNykoQ7LShcxvI0VpYPm9Lix2zpPePnpKGZIexMQd7mxbrMZq+6XmqZg5fO9JsmAJJx0Ra6s8TdguJsUDPrS4+7ogngohRtj1DDfE3djjEZcrpEoFYOFLDxsN2DU1mJW/55VMGvGLa2ONDOcNxZbW6Drql4TaOODXffbX3I6l8tkGmLwCQByu0D4uvxUlpqJUz3C1SpEpKymKqp/YBaAfokFbnicV3FUfytImRlWwUws9QtbDg8BUmmw98+SAP8Hgl2CISVpxQycyNgWlipI+PM2YX/C2GKlARwAFnm3/ME2LFWnChEIqJxHx52n9x9LmI8ydE5IJteV46fSHcXfRhQZHzOtTujv9e/5X9gIVHpHTQ8qyeBsulHXIBvS0ErHhJpPGKHn06HhSB863sHQomvg47XcRCP6ThtDvI2KZtvA6/lUoInOrUeSflOlRYVl/4bGkGKYOpOfpUxhnF8QFIAoUNOVbyCuybsYEbARrlt/Nzc1ZRmItdUcCHbmnvswqVTrhYNWrdxXYfjfNlQQd/A6wyNJeoaYUFaUvcHHU9mJeIN2q/hiqu2XqNK2Dv0D3tVsGMfWpKvjd/5tlTBJmd9FPazLA1bNapMNG1sPg/l5/CojdFjwv02hE0A+09pC+82V/McK0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
