travis:
  secure:
    BINSTAR_TOKEN: Ht/VBKmp/R77UplrhkbU0yoBhvVMTMmBKUbFli4E8B9tXh0ibnM3gd5CBKyUqWmQTW1qRudyR1ILgEhYsufr6OQu/ILlblYmls9hjfnUo0CB9XJb3EmJhlsbzweVO8s2DLZXmNEadOnaVGOvQ96ZPFI4GLxI4kA1mMtCwQvoEdt2W+zEGMYonaTzAsJosVvl3Ung1a9oMZWiro6ygyfBxr1G2GBCGUKiyU3XuB30ZOm6eAITQVApZQpG9LH8Fy+MXXUBGVbj0tkWTnX27aH5FPFngFLYBayS3x8jPLJ9jCsGC4VAPnadCjIKxK7q6r78xg9Y7DKoYgjNKwJBYZldvHT/bRrs9GvF+GkJ5zoFDkbZJJ3icPWyUuodLoLyRQllI2O9bRr1zianPiG+/VYFxita4HDPx4T8QXHTIUY9/uhC33n7ucQIS/qMYPZ59cdg15sJXpWsf1QkiCLA1ns9bq7YWR/EVNjYexuWrPqpdY2g/TMsHj0JLJv22H+IUNQSHlVoUgDEuLgw14rrYtoMOSAdPZ/HxzzaUthN3hnn0d2QSZwy2eP/8IYB8YBch8HyF1bjhC+pgHQZGxf/4mbEOcUZQMswiqzLtnlxidAEh04aEnLrsE37v1l0uGfk69t3lQ9uZkQFsoSYSEOQHggyGCUSwjPICQxCjfWEdAOmH3s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
